config/routes.rb
NewsSystem::Application.routes.draw do

  get "tinymce_assets/create"

  resources :posts do
    collection do
      put 'publish'
    end
  end

  post '/tinymce_assets' => 'tinymce_assets#create'

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :published, :link, :body

  validates :link, :body, presence: true
  validates :link, format: /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :check_if_admin, only: [:new, :edit, :update, :destroy]

  def index
    # @posts = Post.where(published: true)
    @posts = Post.all

    # render text: @posts.map { |p| "#{p.id} | #{p.body}" }.join("<br/>")
  end

  # /posts/1 GET
  def show
    @post = Post.where(id: params[:id]).first

    # render "posts/show"
  end

  # /posts/new GET
  def new
    @post = Post.new
  end

  # /posts/1/edit GET
  def edit
    @post = Post.find(params[:id])
  end

  # /posts POST
  def create
    @post = Post.create(params[:post])

    if @post.errors.empty?
      redirect_to post_path(@post)
    else
      render "new"
    end
  end

  # /posts/1 PUT
  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])

    respond_to do |format|
      if @post.errors.empty?
        format.html { redirect_to post_path(@post) }
        format.js   { render nothing: true }
      else
        format.html { render "edit" }
        format.js   {  }
      end
    end
  end

  # /posts/1 DELETE
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def publish
    ids = [*params[:post_ids]]
    Post.update_all({ published: true }, { id: ids })
    Post.update_all({ published: false }, "posts.id NOT IN (#{ ids.join(',') })")
    #flash[:success] = "Attribute 'published' was updated successfully in posts"

    respond_to do |format|
      format.html { redirect_to posts_path }
      format.json { head :no_content }
    end
  end

  private

    def check_if_admin
      authenticate_or_request_with_http_basic("NewsSystem") do |username, password|
        username == "admin" && password == "admin"
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsSystem</title>
  <!-- [if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"
            type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">News System</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Browse news", posts_path %></li>
          <li><%= link_to "Contact us" %></li>
          <li><%= link_to "About us" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="span8">
        <%= yield %>
      </div>
      <div class="span4">
        <h2>About us</h2>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
          labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
          ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa
          qui officia deserunt mollit anim id est laborum.
        </p>
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= tinymce_assets %>

<%= simple_form_for @post, :html => { :id => 'posts' } do |f| %>
  <% if @post.errors.any? %>
    <div id="errorExplanation">
      <h4><%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:</h4>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :published, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :published, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :link, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, class: "tinymce" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

<%= tinymce %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= form_tag publish_posts_path, method: :put, remote: true do %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:published) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td>
          <%= check_box_tag "post_ids[]", post.id, post.published %>
        </td>
        <% if post.body.length > 30 %>
          <td><%= raw truncate(post.body) %>&nbsp;<%= link_to 'Read more...', post_path(post) %></td>
        <% else %>
          <td><%= raw post.body %></td>
        <% end %>
        <td><%=l post.created_at %></td>
        <td>
          <%= link_to 'preview post', post_path(post), target: '_blank' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

<%= submit_tag "Marked as publish" %>
<% end %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:published) %>:</strong></dt>
  <dd><%= @post.published %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @post.link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= raw @post.body %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>